# To use:
#     pre-commit run -a

# Or:
#     pre-commit install (runs every time you commit in git)

# To update hooks:
#     pre-commit autoupdate

# See https://github.com/pre-commit/pre-commit

repos:

  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        exclude_types: [rst]
      - id: fix-byte-order-marker

  # Python hooks
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
        args: [--line-length=130]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: ["--max-line-length", "130"]

  # Spellcheck in comments and docs
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        args: ['--write-changes']
        exclude: CHANGELOG\.rst|\.(svg|pyc)$

  # CPP hooks
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.6
    hooks:
      - id: clang-format

  - repo: local
    hooks:
      - id: ament_cppcheck
        name: ament_cppcheck
        description: Static code analysis of C/C++ files.
        stages: [commit]
        # entry: env AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS=TRUE ament_cppcheck
        entry: bash -c "source /opt/ros/jazzy/setup.bash && env AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS=TRUE ament_cppcheck"
        language: system
        files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$

  - repo: local
    hooks:
      - id: ament_cpplint
        name: ament_cpplint
        description: Static code analysis of C/C++ files.
        stages: [commit]
        # entry: ament_cpplint
        entry: bash -c "source /opt/ros/jazzy/setup.bash && ament_cpplint"
        language: system
        files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
        args: ["--linelength=100", "--filter=-whitespace/newline"]
